# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(30, 30, 30, -1)
        self.verticalLayout.setSpacing(25)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SelectServiceLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(30)
        self.SelectServiceLabel.setFont(font)
        self.SelectServiceLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SelectServiceLabel.setTextFormat(QtCore.Qt.AutoText)
        self.SelectServiceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectServiceLabel.setObjectName("SelectServiceLabel")
        self.verticalLayout.addWidget(self.SelectServiceLabel)
        self.AddProductBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddProductBtn.sizePolicy().hasHeightForWidth())
        self.AddProductBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("B Roya")
        font.setPointSize(30)
        self.AddProductBtn.setFont(font)
        self.AddProductBtn.setStyleSheet("background-color: rgb(17, 167, 0);\n"
"border-radius: 20px;")
        self.AddProductBtn.setObjectName("AddProductBtn")
        self.verticalLayout.addWidget(self.AddProductBtn)
        self.SellProductBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SellProductBtn.sizePolicy().hasHeightForWidth())
        self.SellProductBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("B Roya")
        font.setPointSize(30)
        self.SellProductBtn.setFont(font)
        self.SellProductBtn.setStyleSheet("background-color: rgb(255, 0, 4);\n"
"border-radius: 20px;")
        self.SellProductBtn.setObjectName("SellProductBtn")
        self.verticalLayout.addWidget(self.SellProductBtn)
        self.LogsBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogsBtn.sizePolicy().hasHeightForWidth())
        self.LogsBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("B Roya")
        font.setPointSize(30)
        self.LogsBtn.setFont(font)
        self.LogsBtn.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"border-radius: 20px;")
        self.LogsBtn.setObjectName("LogsBtn")
        self.verticalLayout.addWidget(self.LogsBtn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SelectServiceLabel.setText(_translate("MainWindow", "انتخاب سرویس"))
        self.AddProductBtn.setText(_translate("MainWindow", "ورود محصول"))
        self.SellProductBtn.setText(_translate("MainWindow", "فروش محصول"))
        self.LogsBtn.setText(_translate("MainWindow", "گزارشات"))
