# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/SellProductSerialCheck.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(30, 30, 30, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(30)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setStyleSheet("background-color: rgb(255, 0, 4);\n"
"border-radius: 20px;\n"
"padding: 20px;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.ProductLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ProductLabel.setFont(font)
        self.ProductLabel.setObjectName("ProductLabel")
        self.verticalLayout.addWidget(self.ProductLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SearchBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(15)
        self.SearchBtn.setFont(font)
        self.SearchBtn.setObjectName("SearchBtn")
        self.horizontalLayout.addWidget(self.SearchBtn)
        self.ProductSerialEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ProductSerialEdit.setFont(font)
        self.ProductSerialEdit.setObjectName("ProductSerialEdit")
        self.horizontalLayout.addWidget(self.ProductSerialEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.ProductSerialList = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ProductSerialList.setFont(font)
        self.ProductSerialList.setObjectName("ProductSerialList")
        self.verticalLayout.addWidget(self.ProductSerialList)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(32)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CancelBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CancelBtn.sizePolicy().hasHeightForWidth())
        self.CancelBtn.setSizePolicy(sizePolicy)
        self.CancelBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(20)
        self.CancelBtn.setFont(font)
        self.CancelBtn.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(175, 0, 0);")
        self.CancelBtn.setObjectName("CancelBtn")
        self.horizontalLayout_2.addWidget(self.CancelBtn)
        self.NextBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NextBtn.sizePolicy().hasHeightForWidth())
        self.NextBtn.setSizePolicy(sizePolicy)
        self.NextBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(20)
        self.NextBtn.setFont(font)
        self.NextBtn.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(0, 117, 14);")
        self.NextBtn.setObjectName("NextBtn")
        self.horizontalLayout_2.addWidget(self.NextBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_12.setText(_translate("MainWindow", "فرم فروش محصول"))
        self.ProductLabel.setText(_translate("MainWindow", "هیچ محصولی پیدا نشد"))
        self.SearchBtn.setText(_translate("MainWindow", "جستجو"))
        self.ProductSerialEdit.setPlaceholderText(_translate("MainWindow", "Serial"))
        self.CancelBtn.setText(_translate("MainWindow", "لغو"))
        self.NextBtn.setText(_translate("MainWindow", "بعدی"))
